name: Docker Image CI

on:
  push:
    branches: [ "Dev" ]
  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build & push docker image 
      run: |
           echo "${{ secrets.DOCKERS }}"  | docker login -u "skillassure" --password-stdin
           docker build -t skillassure/github:1 .
           docker push skillassure/github:1
    
